# Generated by Django 5.0.6 on 2026-02-10 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_must_change_password_alter_parent_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="parent_profiles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ParentTeacherMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_initiated",
                    models.BooleanField(default=True, help_text="True if parent sent, False if teacher sent"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_pt_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_pt_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The child this message is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_teacher_messages",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent-Teacher Message",
                "verbose_name_plural": "Parent-Teacher Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionSlip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("signed", "Signed"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("parent_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Staff member who created this slip",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_permission_slips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_slips",
                        to="accounts.parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_slips",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Slip",
                "verbose_name_plural": "Permission Slips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentTeacherAppointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("08:00-08:30", "08:00 - 08:30"),
                            ("08:30-09:00", "08:30 - 09:00"),
                            ("09:00-09:30", "09:00 - 09:30"),
                            ("09:30-10:00", "09:30 - 10:00"),
                            ("10:00-10:30", "10:00 - 10:30"),
                            ("10:30-11:00", "10:30 - 11:00"),
                            ("11:00-11:30", "11:00 - 11:30"),
                            ("11:30-12:00", "11:30 - 12:00"),
                            ("13:00-13:30", "13:00 - 13:30"),
                            ("13:30-14:00", "13:30 - 14:00"),
                            ("14:00-14:30", "14:00 - 14:30"),
                            ("14:30-15:00", "14:30 - 15:00"),
                            ("15:00-15:30", "15:00 - 15:30"),
                            ("15:30-16:00", "15:30 - 16:00"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for the appointment")),
                ("notes", models.TextField(blank=True, help_text="Teacher notes after the meeting")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="accounts.parent"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_appointments",
                        to="accounts.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "professor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent-Teacher Appointment",
                "verbose_name_plural": "Parent-Teacher Appointments",
                "ordering": ["-date", "time_slot"],
                "unique_together": {("teacher", "date", "time_slot")},
            },
        ),
    ]
