# Generated by Django 5.0.6 on 2026-01-05 18:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_drop_reason_student_graduation_date_and_more'),
        ('core', '0004_school_remove_newsandevents_summary_ru_and_more'),
        ('course', '0005_remove_course_summary_ru_remove_course_title_ru_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_gateway', models.CharField(choices=[('stripe', 'Stripe'), ('braintree', 'Braintree'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=20)),
                ('transaction_id', models.CharField(help_text='Payment gateway transaction ID', max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('number_of_installments', models.PositiveIntegerField(help_text='Number of installment payments', validators=[django.core.validators.MinValueValidator(1)])),
                ('installment_amount', models.DecimalField(decimal_places=2, help_text='Amount per installment', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
            },
        ),
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes about the verification')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Verification',
                'verbose_name_plural': 'Payment Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Unique receipt number', max_length=100, unique=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF receipt', upload_to='receipts/%Y/%m/%d/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_email', models.BooleanField(default=False, help_text='Receipt sent to student email')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, help_text='Invoice description'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Payment due date', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.semester'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Associated student for fee invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('phd', 'PhD/Doctoral'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], help_text='Academic level (Bachelor, Master, etc.)', max_length=25)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024-2025)', max_length=20)),
                ('tuition_fee', models.DecimalField(decimal_places=2, help_text='Tuition fee amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('registration_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time registration fee', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('library_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('lab_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sports_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='course.program')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['-academic_year', 'program', 'level'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_structure',
            field=models.ForeignKey(blank=True, help_text='Associated fee structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='payments.feestructure'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student', '-created_at'], name='payments_in_student_810da4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_complete', 'due_date'], name='payments_in_payment_10ee6e_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment',
            field=models.ForeignKey(blank=True, help_text='Associated installment if part of payment plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.installment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.invoice'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='payments.invoice'),
        ),
        migrations.AddField(
            model_name='installment',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.paymentplan'),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['program', 'level', 'academic_year'], name='payments_fe_program_9cf6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['is_active', '-academic_year'], name='payments_fe_is_acti_751f28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('program', 'level', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', '-payment_date'], name='payments_pa_invoice_679b41_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-payment_date'], name='payments_pa_status_626cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('payment_plan', 'installment_number')},
        ),
    ]
