# Generated by Django 5.0.6 on 2026-02-12 06:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("course", "0001_initial"),
        ("filieres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Room Name")),
                ("name_en", models.CharField(max_length=100, null=True, verbose_name="Room Name")),
                ("name_fr", models.CharField(max_length=100, null=True, verbose_name="Room Name")),
                ("name_es", models.CharField(max_length=100, null=True, verbose_name="Room Name")),
                ("code", models.CharField(max_length=20, verbose_name="Room Code")),
                ("building", models.CharField(blank=True, max_length=100, verbose_name="Building")),
                ("floor", models.IntegerField(default=0, verbose_name="Floor")),
                (
                    "capacity",
                    models.IntegerField(
                        default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Capacity"
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("classroom", "Classroom"),
                            ("lab", "Laboratory"),
                            ("amphitheatre", "Amphitheatre"),
                            ("computer_room", "Computer Room"),
                            ("meeting", "Meeting Room"),
                            ("gym", "Gymnasium"),
                            ("online", "Online/Virtual"),
                        ],
                        default="classroom",
                        max_length=20,
                        verbose_name="Room Type",
                    ),
                ),
                (
                    "equipment",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of equipment: ["projector", "whiteboard", "computers"]',
                        verbose_name="Equipment",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rooms", to="core.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["building", "floor", "name"],
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "group_name",
                    models.CharField(
                        blank=True, help_text='e.g. "Group A", "TD1"', max_length=50, verbose_name="Group"
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="Effective From")),
                ("effective_until", models.DateField(verbose_name="Effective Until")),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly_odd", "Bi-weekly (Odd weeks)"),
                            ("biweekly_even", "Bi-weekly (Even weeks)"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="Recurrence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("substituted", "Substituted"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("color", models.CharField(default="#3788d8", max_length=7, verbose_name="Color")),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked entries are preserved during auto-regeneration",
                        verbose_name="Locked",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schedule_entries", to="course.course"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedule_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="filieres.filiere",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"role": "professor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_entries",
                        to="scheduling.room",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="core.semester",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="core.session",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schedule_entries", to="core.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Entry",
                "verbose_name_plural": "Schedule Entries",
                "ordering": ["time_slot__day_of_week", "time_slot__start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("cancellation", "Cancellation"),
                            ("room_change", "Room Change"),
                            ("substitution", "Substitution"),
                            ("reschedule", "Reschedule"),
                            ("extra_session", "Extra Session"),
                        ],
                        max_length=20,
                        verbose_name="Exception Type",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("new_start_time", models.TimeField(blank=True, null=True, verbose_name="New Start Time")),
                ("new_end_time", models.TimeField(blank=True, null=True, verbose_name="New End Time")),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                ("is_approved", models.BooleanField(default=False, verbose_name="Approved")),
                ("notify_students", models.BooleanField(default=True, verbose_name="Notify Students")),
                ("notification_sent", models.BooleanField(default=False, verbose_name="Notification Sent")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_schedule_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedule_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override room for this date",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exception_assignments",
                        to="scheduling.room",
                    ),
                ),
                (
                    "schedule_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="scheduling.scheduleentry",
                    ),
                ),
                (
                    "substitute_professor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Substitute professor for this date",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substitution_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Exception",
                "verbose_name_plural": "Schedule Exceptions",
                "ordering": ["-date"],
                "unique_together": {("schedule_entry", "date", "exception_type")},
            },
        ),
        migrations.CreateModel(
            name="SubstitutionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Date")),
                ("reason", models.TextField(verbose_name="Reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("fulfilled", "Fulfilled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_substitute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substitution_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requesting_professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_substitution_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_requests",
                        to="scheduling.scheduleentry",
                    ),
                ),
                (
                    "suggested_substitute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substitution_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_requests",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Substitution Request",
                "verbose_name_plural": "Substitution Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Slot Name")),
                ("name_en", models.CharField(max_length=50, null=True, verbose_name="Slot Name")),
                ("name_fr", models.CharField(max_length=50, null=True, verbose_name="Slot Name")),
                ("name_es", models.CharField(max_length=50, null=True, verbose_name="Slot Name")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[("class", "Class Period"), ("break", "Break"), ("lunch", "Lunch Break")],
                        default="class",
                        max_length=10,
                        verbose_name="Slot Type",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="time_slots", to="core.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "ordering": ["day_of_week", "order", "start_time"],
                "unique_together": {("tenant", "day_of_week", "start_time")},
            },
        ),
        migrations.AddField(
            model_name="scheduleentry",
            name="time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="schedule_entries", to="scheduling.timeslot"
            ),
        ),
        migrations.CreateModel(
            name="TimetableGeneration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Constraints and preferences used for generation",
                        verbose_name="Configuration",
                    ),
                ),
                ("entries_created", models.IntegerField(default=0, verbose_name="Entries Created")),
                ("conflicts_found", models.IntegerField(default=0, verbose_name="Conflicts Found")),
                ("conflict_details", models.JSONField(blank=True, default=list, verbose_name="Conflict Details")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Only one published generation per session+semester",
                        verbose_name="Published",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_generations",
                        to="core.semester",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_generations",
                        to="core.session",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_generations",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Generation",
                "verbose_name_plural": "Timetable Generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="scheduleentry",
            name="generation",
            field=models.ForeignKey(
                blank=True,
                help_text="The generation run that created this entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="scheduling.timetablegeneration",
            ),
        ),
        migrations.CreateModel(
            name="ScheduleNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("cancellation", "Class Cancelled"),
                            ("room_change", "Room Changed"),
                            ("substitution", "Substitute Teacher"),
                            ("reschedule", "Class Rescheduled"),
                            ("new_event", "New Event"),
                            ("reminder", "Reminder"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False, verbose_name="Email Sent")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="scheduling.scheduleentry",
                    ),
                ),
                (
                    "related_exception",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="scheduling.scheduleexception",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_notifications",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Notification",
                "verbose_name_plural": "Schedule Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient", "is_read"], name="scheduling__recipie_6019dd_idx"),
                    models.Index(fields=["tenant", "-created_at"], name="scheduling__tenant__27e782_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfessorAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("unavailable", "Unavailable"),
                            ("avoid", "Prefer to Avoid"),
                            ("neutral", "Neutral"),
                            ("preferred", "Preferred"),
                        ],
                        default="neutral",
                        max_length=20,
                        verbose_name="Preference",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor_preferences",
                        to="scheduling.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor Availability",
                "verbose_name_plural": "Professor Availabilities",
                "unique_together": {("professor", "time_slot")},
            },
        ),
        migrations.AddIndex(
            model_name="scheduleentry",
            index=models.Index(fields=["tenant", "professor"], name="scheduling__tenant__3f158a_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduleentry",
            index=models.Index(fields=["tenant", "room"], name="scheduling__tenant__422985_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduleentry",
            index=models.Index(fields=["tenant", "filiere", "semester"], name="scheduling__tenant__8a00a8_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduleentry",
            index=models.Index(fields=["effective_from", "effective_until"], name="scheduling__effecti_706a4d_idx"),
        ),
    ]
