# Generated by Django 5.0.6 on 2026-01-05 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_student_drop_reason_student_graduation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField()),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('current_occupation', models.CharField(blank=True, max_length=200)),
                ('current_employer', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('personal_email', models.EmailField(blank=True, help_text='Personal email (not school email)', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Active in alumni network')),
                ('willing_to_mentor', models.BooleanField(default=False)),
                ('newsletter_subscribed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about alumni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_record', to='accounts.student')),
            ],
            options={
                'verbose_name_plural': 'Alumni',
                'ordering': ['-graduation_year', 'student__student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='AlumniAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('award', 'Award/Recognition'), ('publication', 'Publication'), ('promotion', 'Career Promotion'), ('entrepreneurship', 'Started Business'), ('community_service', 'Community Service'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achievement_date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='alumni/achievements/%Y/%m/')),
                ('url', models.URLField(blank=True, help_text='Link to news article or announcement')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on alumni page')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='alumni.alumni')),
            ],
            options={
                'ordering': ['-achievement_date'],
            },
        ),
        migrations.CreateModel(
            name='AlumniDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('purpose', models.CharField(choices=[('general', 'General Fund'), ('scholarship', 'Scholarship Fund'), ('infrastructure', 'Infrastructure'), ('research', 'Research'), ('sports', 'Sports'), ('library', 'Library'), ('other', 'Other')], default='general', max_length=20)),
                ('purpose_details', models.TextField(blank=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('braintree', 'Braintree'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash')], max_length=50)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('tax_receipt_sent', models.BooleanField(default=False)),
                ('tax_receipt_number', models.CharField(blank=True, max_length=100)),
                ('thank_you_sent', models.BooleanField(default=False)),
                ('thank_you_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='alumni.alumni')),
            ],
            options={
                'ordering': ['-donated_at'],
            },
        ),
        migrations.CreateModel(
            name='AlumniEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('reunion', 'Reunion'), ('networking', 'Networking'), ('workshop', 'Workshop'), ('social', 'Social Gathering'), ('fundraiser', 'Fundraiser'), ('career_fair', 'Career Fair'), ('other', 'Other')], default='other', max_length=20)),
                ('event_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('venue_details', models.TextField(blank=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events_attended', to='alumni.alumni')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_alumni_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['graduation_year'], name='alumni_alum_graduat_36e3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['is_active'], name='alumni_alum_is_acti_f872e0_idx'),
        ),
        migrations.AddIndex(
            model_name='alumniachievement',
            index=models.Index(fields=['-achievement_date'], name='alumni_alum_achieve_0f63d5_idx'),
        ),
        migrations.AddIndex(
            model_name='alumniachievement',
            index=models.Index(fields=['is_featured', '-achievement_date'], name='alumni_alum_is_feat_deaab9_idx'),
        ),
        migrations.AddIndex(
            model_name='alumnidonation',
            index=models.Index(fields=['-donated_at'], name='alumni_alum_donated_cc39d5_idx'),
        ),
        migrations.AddIndex(
            model_name='alumnidonation',
            index=models.Index(fields=['purpose', '-donated_at'], name='alumni_alum_purpose_b4c2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='alumnievent',
            index=models.Index(fields=['-event_date'], name='alumni_alum_event_d_17bf07_idx'),
        ),
        migrations.AddIndex(
            model_name='alumnievent',
            index=models.Index(fields=['event_type', '-event_date'], name='alumni_alum_event_t_64a942_idx'),
        ),
    ]
