# Generated by Django 5.0.6 on 2026-01-05 18:49

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsandevents_summary_es_newsandevents_summary_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('license_key', models.CharField(max_length=100, unique=True)),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('subscription_start', models.DateField()),
                ('subscription_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_students', models.IntegerField(default=500)),
                ('max_staff', models.IntegerField(default=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School (Tenant)',
                'verbose_name_plural': 'Schools (Tenants)',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_ru',
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
