# Generated by Django 5.0.6 on 2026-02-12 15:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0010_parent_custody_notes_parent_effective_from_and_more"),
        ("core", "0001_initial"),
        ("discipline", "0002_disciplinaryaction_parent_acknowledged_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("medical", "Medical Emergency"),
                            ("accident", "Accident/Injury"),
                            ("theft", "Theft"),
                            ("vandalism", "Vandalism"),
                            ("confrontation", "Confrontation"),
                            ("police", "Police Visit"),
                            ("complaint", "External Complaint"),
                            ("safeguarding", "Safeguarding Concern"),
                            ("behavioral", "Behavioral"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Incident Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Brief summary of the incident", max_length=200, verbose_name="Title"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Under Investigation"),
                            ("action_taken", "Action Taken"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("incident_date", models.DateField(verbose_name="Incident Date")),
                ("incident_time", models.TimeField(blank=True, null=True, verbose_name="Incident Time")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Where the incident occurred (e.g., Room 204, Playground)",
                        max_length=200,
                        verbose_name="Location",
                    ),
                ),
                (
                    "external_parties",
                    models.TextField(
                        blank=True,
                        help_text="Names and details of external people involved",
                        verbose_name="External Parties",
                    ),
                ),
                (
                    "witnesses",
                    models.TextField(blank=True, help_text="Names and details of witnesses", verbose_name="Witnesses"),
                ),
                ("actions_taken", models.TextField(blank=True, verbose_name="Actions Taken")),
                ("follow_up_needed", models.BooleanField(default=False, verbose_name="Follow-up Needed")),
                ("follow_up_date", models.DateField(blank=True, null=True, verbose_name="Follow-up Date")),
                ("follow_up_notes", models.TextField(blank=True, verbose_name="Follow-up Notes")),
                ("resolution", models.TextField(blank=True, verbose_name="Resolution")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disciplinary_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_incidents",
                        to="discipline.disciplinaryaction",
                        verbose_name="Related Disciplinary Action",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents_reported",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reported By",
                    ),
                ),
                (
                    "staff_involved",
                    models.ManyToManyField(
                        blank=True,
                        related_name="incidents_involved_as_staff",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Staff Involved",
                    ),
                ),
                (
                    "students_involved",
                    models.ManyToManyField(
                        blank=True,
                        related_name="incidents_involved",
                        to="accounts.student",
                        verbose_name="Students Involved",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="incidents", to="core.school"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "ordering": ["-incident_date", "-created_at"],
                "permissions": [
                    ("view_all_incidents", "Can view all incidents"),
                    ("close_incident", "Can close incidents"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IncidentAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        upload_to="safeguarding/incidents/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx", "jpg", "jpeg", "png", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of the attachment",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="safeguarding.incident",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Attachment",
                "verbose_name_plural": "Incident Attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentCaseNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("behavioral", "Behavioral"),
                            ("family", "Family"),
                            ("medical", "Medical"),
                            ("legal", "Legal"),
                            ("counseling", "Counseling"),
                            ("general", "General"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("restricted", "Restricted"),
                            ("highly_restricted", "Highly Restricted"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Confidentiality Level",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Note Content")),
                ("follow_up_date", models.DateField(blank=True, null=True, verbose_name="Follow-up Date")),
                ("follow_up_completed", models.BooleanField(default=False, verbose_name="Follow-up Completed")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_notes_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "related_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_notes",
                        to="safeguarding.incident",
                        verbose_name="Related Incident",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_notes",
                        to="accounts.student",
                        verbose_name="Student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="case_notes", to="core.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Case Note",
                "verbose_name_plural": "Student Case Notes",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_restricted_notes", "Can view restricted case notes"),
                    ("view_highly_restricted_notes", "Can view highly restricted case notes"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("visitor_name", models.CharField(max_length=200, verbose_name="Visitor Name")),
                (
                    "visitor_type",
                    models.CharField(
                        choices=[
                            ("parent", "Parent/Guardian"),
                            ("police", "Police Officer"),
                            ("social_worker", "Social Worker"),
                            ("inspector", "School Inspector"),
                            ("contractor", "Contractor/Vendor"),
                            ("government", "Government Official"),
                            ("media", "Media"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Visitor Type",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Police department, social services agency, etc.",
                        max_length=200,
                        verbose_name="Organization",
                    ),
                ),
                (
                    "badge_number",
                    models.CharField(
                        blank=True,
                        help_text="Official badge or ID number for officials",
                        max_length=50,
                        verbose_name="Badge/ID Number",
                    ),
                ),
                (
                    "id_verified",
                    models.BooleanField(
                        default=False, help_text="Was official identification checked?", verbose_name="ID Verified"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30, verbose_name="Contact Phone")),
                ("purpose", models.TextField(verbose_name="Purpose of Visit")),
                ("time_in", models.DateTimeField(verbose_name="Time In")),
                ("time_out", models.DateTimeField(blank=True, null=True, verbose_name="Time Out")),
                ("notes", models.TextField(blank=True, verbose_name="Notes/Outcome")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_visitors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "host_staff",
                    models.ForeignKey(
                        help_text="Primary staff member the visitor met with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_visitors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Staff Member Met",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_logs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged By",
                    ),
                ),
                (
                    "related_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_logs",
                        to="safeguarding.incident",
                        verbose_name="Related Incident",
                    ),
                ),
                (
                    "students_involved",
                    models.ManyToManyField(
                        blank=True, related_name="visitor_logs", to="accounts.student", verbose_name="Students Involved"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="visitor_logs", to="core.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitor Log",
                "verbose_name_plural": "Visitor Logs",
                "ordering": ["-time_in"],
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["tenant", "status", "-incident_date"], name="sg_incident_status_idx"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["tenant", "incident_type"], name="sg_incident_type_idx"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["tenant", "severity"], name="sg_incident_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="studentcasenote",
            index=models.Index(fields=["tenant", "student", "-created_at"], name="sg_casenote_student_idx"),
        ),
        migrations.AddIndex(
            model_name="studentcasenote",
            index=models.Index(fields=["tenant", "category"], name="sg_casenote_category_idx"),
        ),
        migrations.AddIndex(
            model_name="studentcasenote",
            index=models.Index(fields=["follow_up_date"], name="sg_casenote_followup_idx"),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(fields=["tenant", "-time_in"], name="sg_visitor_time_idx"),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(fields=["tenant", "visitor_type"], name="sg_visitor_type_idx"),
        ),
    ]
