# Generated by Django 5.0.6 on 2026-01-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_ru',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('phd', 'PhD/Doctoral'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('fall', 'Fall Semester'), ('spring', 'Spring Semester'), ('summer', 'Summer Semester')], max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], default=1),
        ),
    ]
