# Generated by Django 5.0.6 on 2026-01-05 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_essayquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('correct_answer', models.BooleanField(default=True, help_text='Select True or False as the correct answer', verbose_name='Correct Answer')),
            ],
            options={
                'verbose_name': 'True/False Question',
                'verbose_name_plural': 'True/False Questions',
            },
            bases=('quiz.question',),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit for completing the quiz in minutes. Leave blank for no time limit.', null=True, verbose_name='Time Limit (minutes)'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='time_spent',
            field=models.DurationField(blank=True, help_text='Total time spent on the quiz', null=True, verbose_name='Time Spent'),
        ),
    ]
