# Generated by Django 5.0.6 on 2026-02-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionstudent",
            name="address",
        ),
        migrations.RemoveField(
            model_name="admissionstudent",
            name="guardian_name",
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="guardian_first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="guardian_last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="guardian_middle_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="province",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="admissionstudent",
            name="street_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
