# Generated by Django 5.0.6 on 2026-01-26 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assessment_method', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('project', 'Project'), ('exam', 'Exam'), ('discussion', 'Discussion Participation')], max_length=50)),
                ('target_percentage', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='course.course')),
            ],
            options={
                'ordering': ['course', 'outcome_name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('page_view', 'Page View'), ('video_view', 'Video View'), ('download', 'File Download'), ('quiz_start', 'Quiz Started'), ('quiz_submit', 'Quiz Submitted'), ('assignment_submit', 'Assignment Submitted'), ('forum_post', 'Forum Post'), ('forum_reply', 'Forum Reply'), ('search', 'Search'), ('other', 'Other')], max_length=50)),
                ('activity_description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='analytics_a_student_46cc51_idx'), models.Index(fields=['course', 'activity_type', '-created_at'], name='analytics_a_course__9fdb7b_idx'), models.Index(fields=['activity_type', '-created_at'], name='analytics_a_activit_c99d4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AtRiskStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical')], max_length=20)),
                ('risk_score', models.DecimalField(decimal_places=2, help_text='0-100 scale', max_digits=5)),
                ('low_engagement', models.BooleanField(default=False)),
                ('low_attendance', models.BooleanField(default=False)),
                ('failing_grades', models.BooleanField(default=False)),
                ('no_recent_activity', models.BooleanField(default=False)),
                ('missing_assignments', models.PositiveIntegerField(default=0)),
                ('intervention_needed', models.BooleanField(default=True)),
                ('intervention_notes', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacted_students', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_risk_students', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='accounts.student')),
            ],
            options={
                'ordering': ['-risk_score', '-identified_at'],
                'indexes': [models.Index(fields=['course', '-risk_score'], name='analytics_a_course__82809b_idx'), models.Index(fields=['risk_level', 'is_active'], name='analytics_a_risk_le_576492_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_modules', models.PositiveIntegerField(default=0)),
                ('completed_modules', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total minutes spent')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_completions', to='accounts.student')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['student', 'is_completed'], name='analytics_c_student_6dfdf2_idx'), models.Index(fields=['course', '-completion_percentage'], name='analytics_c_course__e7d085_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='OutcomeMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment_name', models.CharField(max_length=200)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meets_target', models.BooleanField(default=False)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='analytics.learningoutcome')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_measurements', to='accounts.student')),
            ],
            options={
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['outcome', 'meets_target'], name='analytics_o_outcome_eee1f0_idx'), models.Index(fields=['student', '-assessed_at'], name='analytics_o_student_27a27a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('total_time_minutes', models.PositiveIntegerField(default=0)),
                ('pages_viewed', models.PositiveIntegerField(default=0)),
                ('videos_watched', models.PositiveIntegerField(default=0)),
                ('documents_downloaded', models.PositiveIntegerField(default=0)),
                ('forum_posts', models.PositiveIntegerField(default=0)),
                ('forum_replies', models.PositiveIntegerField(default=0)),
                ('questions_asked', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('quizzes_attempted', models.PositiveIntegerField(default=0)),
                ('quizzes_completed', models.PositiveIntegerField(default=0)),
                ('assignments_submitted', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='accounts.student')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student', '-date'], name='analytics_s_student_337feb_idx'), models.Index(fields=['course', '-date'], name='analytics_s_course__56d57c_idx'), models.Index(fields=['-engagement_score'], name='analytics_s_engagem_f5e17a_idx')],
                'unique_together': {('student', 'course', 'date')},
            },
        ),
    ]
