# Generated by Django 5.0.6 on 2026-02-13 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("attendance_anomaly", "Attendance Anomaly"),
                            ("engagement_drop", "Engagement Drop"),
                            ("payment_shortfall", "Payment Shortfall"),
                            ("risk_cluster", "At-Risk Cluster"),
                            ("grade_trend", "Grade Trend"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("critical", "Critical")],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dismissed_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(fields=["insight_type", "is_active"], name="analytics_i_insight_e33b3c_idx"),
                    models.Index(fields=["-generated_at"], name="analytics_i_generat_9158d9_idx"),
                ],
            },
        ),
    ]
