# Generated by Django 5.0.6 on 2026-01-05 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_student_drop_reason_student_graduation_date_and_more'),
        ('course', '0005_remove_course_summary_ru_remove_course_title_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_file', models.FileField(help_text='HTML/PDF template file', upload_to='certificates/templates/%Y/%m/')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for certificate', upload_to='certificates/backgrounds/')),
                ('title_text', models.CharField(default='Certificate of Completion', max_length=200)),
                ('body_template', models.TextField(help_text='Template with placeholders: {student_name}, {course_name}, {date}, {grade}')),
                ('signature_1_name', models.CharField(blank=True, help_text='e.g., Dean', max_length=100)),
                ('signature_1_title', models.CharField(blank=True, max_length=100)),
                ('signature_1_image', models.ImageField(blank=True, upload_to='certificates/signatures/')),
                ('signature_2_name', models.CharField(blank=True, help_text='e.g., Director', max_length=100)),
                ('signature_2_title', models.CharField(blank=True, max_length=100)),
                ('signature_2_image', models.ImageField(blank=True, upload_to='certificates/signatures/')),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=20)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter')], default='A4', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF certificate', upload_to='certificates/issued/%Y/%m/')),
                ('hash_signature', models.CharField(blank=True, help_text='SHA-256 hash of certificate content', max_length=64)),
                ('blockchain_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66)),
                ('qr_code', models.ImageField(blank=True, upload_to='certificates/qr_codes/')),
                ('verification_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Generation'), ('generated', 'Generated'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='course.course')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.student')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchCertificateGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_grade', models.CharField(blank=True, help_text='Minimum grade requirement', max_length=10)),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_generations', to='course.course')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_batch_generations', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verification_method', models.CharField(choices=[('qr_code', 'QR Code Scan'), ('number', 'Certificate Number'), ('hash', 'Hash Verification'), ('blockchain', 'Blockchain Verification')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_valid', models.BooleanField()),
                ('verification_notes', models.TextField(blank=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='certificates.certificate')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student', '-issue_date'], name='certificate_student_9d83d9_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['course', '-issue_date'], name='certificate_course__e3c5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='certificate_certifi_cd0c46_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status', '-created_at'], name='certificate_status_c14213_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='certificateverification',
            index=models.Index(fields=['certificate', '-verified_at'], name='certificate_certifi_3396ba_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateverification',
            index=models.Index(fields=['-verified_at'], name='certificate_verifie_9d58e9_idx'),
        ),
    ]
