# Generated by Django 5.0.6 on 2026-01-26 05:25

import accounts.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('-user__date_joined',),
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relation_ship', models.TextField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grand mother', 'Grand mother'), ('Grand father', 'Grand father'), ('Other', 'Other')])),
            ],
            options={
                'ordering': ('-user__date_joined',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree')], max_length=25, null=True)),
                ('is_alumni', models.BooleanField(default=False, help_text='Mark as True when student graduates')),
                ('is_dropped', models.BooleanField(default=False, help_text='Mark as True when student drops out')),
                ('drop_reason', models.TextField(blank=True, help_text='Reason for dropping out')),
                ('graduation_date', models.DateField(blank=True, help_text='Date of graduation', null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Auto-generated student ID (e.g., 24-CS-001)', max_length=50, unique=True)),
            ],
            options={
                'ordering': ('-student__date_joined',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_lecturer', models.BooleanField(default=False)),
                ('is_parent', models.BooleanField(default=False)),
                ('is_dep_head', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('professor', 'Professor'), ('direction', 'Direction'), ('admin', 'Administrator')], default='student', help_text='User role within the tenant', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('picture', models.ImageField(default='default.png', null=True, upload_to='profile_pictures/%y/%m/%d/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=60, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=60, null=True)),
                ('approval_status', models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='not_requested', help_text='Account approval status', max_length=20)),
                ('requested_role', models.CharField(blank=True, choices=[('parent', 'Parent'), ('student', 'Student'), ('professor', 'Professor'), ('direction', 'Direction'), ('admin', 'Administrator')], help_text='Role requested during registration', max_length=20)),
                ('approval_extra_note', models.TextField(blank=True, help_text='Additional notes for approval/rejection')),
                ('employee_or_student_id', models.CharField(blank=True, help_text='Unique employee or student ID', max_length=50, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth for age verification', null=True)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Country of residence', max_length=2, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, help_text='School/tenant this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.school')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
