# Generated by Django 5.0.6 on 2026-01-05 18:49

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0004_school_remove_newsandevents_summary_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='drop_reason',
            field=models.TextField(blank=True, help_text='Reason for dropping out'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, help_text='Date of graduation', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_alumni',
            field=models.BooleanField(default=False, help_text='Mark as True when student graduates'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_dropped',
            field=models.BooleanField(default=False, help_text='Mark as True when student drops out'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Auto-generated student ID (e.g., 24-CS-001)', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_extra_note',
            field=models.TextField(blank=True, help_text='Additional notes for approval/rejection'),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='not_requested', help_text='Account approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of residence', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age verification', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_or_student_id',
            field=models.CharField(blank=True, help_text='Unique employee or student ID', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('student', 'Student'), ('professor', 'Professor'), ('direction', 'Direction'), ('admin', 'Administrator')], help_text='Role requested during registration', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('professor', 'Professor'), ('direction', 'Direction'), ('admin', 'Administrator')], default='student', help_text='User role within the tenant', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='School/tenant this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.school'),
        ),
    ]
