# Generated by Django 5.0.6 on 2026-02-10 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False, help_text="Force password change on next login"),
        ),
        migrations.AlterField(
            model_name="parent",
            name="student",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="parents", to="accounts.student"
            ),
        ),
        migrations.CreateModel(
            name="InvitationCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique invitation code (format: XXXX-XXXX)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("parent", "Parent"), ("professor", "Professor"), ("direction", "Direction")],
                        help_text="Role assigned when this code is redeemed",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="Code expiration date/time")),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("sent_to_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Student this parent invitation is linked to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_codes",
                        to="accounts.student",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_invitation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation Code",
                "verbose_name_plural": "Invitation Codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
