# Generated by Django 5.0.6 on 2026-02-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_invitationcode_role_alter_user_requested_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Parent"),
                    ("professor", "Professor"),
                    ("prefet", "Discipline Officer"),
                    ("accountant", "Accountant"),
                    ("direction", "Direction"),
                ],
                help_text="Role assigned when this code is redeemed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="requested_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("parent", "Parent"),
                    ("student", "Student"),
                    ("professor", "Professor"),
                    ("prefet", "Discipline Officer"),
                    ("accountant", "Accountant"),
                    ("direction", "Direction"),
                    ("admin", "Administrator"),
                ],
                help_text="Role requested during registration",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Parent"),
                    ("student", "Student"),
                    ("professor", "Professor"),
                    ("prefet", "Discipline Officer"),
                    ("accountant", "Accountant"),
                    ("direction", "Direction"),
                    ("admin", "Administrator"),
                ],
                default="student",
                help_text="User role within the tenant",
                max_length=20,
            ),
        ),
    ]
