# Generated by Django 5.0.6 on 2026-02-12 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_city_user_middle_name_user_postal_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="custody_notes",
            field=models.TextField(blank=True, help_text="Notes about custody arrangement"),
        ),
        migrations.AddField(
            model_name="parent",
            name="effective_from",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date this guardianship became effective",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parent",
            name="effective_until",
            field=models.DateField(blank=True, help_text="Date this guardianship ended (null = current)", null=True),
        ),
        migrations.AddField(
            model_name="parent",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether this guardianship is currently active"),
        ),
        migrations.AddField(
            model_name="parent",
            name="is_primary",
            field=models.BooleanField(default=False, help_text="Primary guardian for the student"),
        ),
    ]
