# Generated by Django 5.0.6 on 2026-02-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinaryaction",
            name="parent_acknowledged",
            field=models.BooleanField(default=False, verbose_name="Parent Acknowledged"),
        ),
        migrations.AddField(
            model_name="disciplinaryaction",
            name="parent_acknowledged_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Acknowledged At"),
        ),
        migrations.AddField(
            model_name="disciplinaryaction",
            name="parent_response",
            field=models.TextField(blank=True, verbose_name="Parent Response"),
        ),
    ]
