# Generated by Django 5.0.6 on 2026-02-06 12:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("course", "0001_initial"),
        ("filieres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("participation", "Class Participation"),
                            ("homework", "Homework/Assignment"),
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm Exam"),
                            ("final", "Final Exam"),
                            ("project", "Project"),
                            ("presentation", "Presentation"),
                            ("behavior", "Behavior"),
                            ("attendance", "Attendance"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Note Type",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Score out of 100",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Score",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100"), max_digits=5, verbose_name="Maximum Score"
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Coefficient from filiere configuration",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                        verbose_name="Coefficient",
                    ),
                ),
                (
                    "weighted_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        null=True,
                        verbose_name="Weighted Score",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Professor Comment")),
                (
                    "private_note",
                    models.TextField(
                        blank=True, help_text="Internal note, not visible to student", verbose_name="Private Note"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("submitted_for_approval", models.BooleanField(default=False, verbose_name="Submitted for Approval")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved At")),
                ("approval_notes", models.TextField(blank=True, verbose_name="Approval Notes")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Is Deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filieres.filiere",
                        verbose_name="Filiere/Program",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["professor", "direction"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Professor",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.semester",
                        verbose_name="Semester",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.session",
                        verbose_name="Academic Session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course", verbose_name="Subject/Course"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="professor_notes", to="core.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor Note",
                "verbose_name_plural": "Professor Notes",
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_note", "Can approve professor notes"),
                    ("view_all_notes", "Can view all notes"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NoteHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("submitted", "Submitted for Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                            ("soft_deleted", "Soft Deleted"),
                        ],
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("old_values", models.JSONField(blank=True, default=dict, verbose_name="Old Values")),
                ("new_values", models.JSONField(blank=True, default=dict, verbose_name="New Values")),
                ("change_summary", models.TextField(blank=True, verbose_name="Change Summary")),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="history", to="notes.professornote"
                    ),
                ),
            ],
            options={
                "verbose_name": "Note History",
                "verbose_name_plural": "Note Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(verbose_name="Comment")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="notes.professornote"
                    ),
                ),
            ],
            options={
                "verbose_name": "Note Comment",
                "verbose_name_plural": "Note Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="professornote",
            index=models.Index(fields=["tenant", "student", "status"], name="notes_profe_tenant__750bc1_idx"),
        ),
        migrations.AddIndex(
            model_name="professornote",
            index=models.Index(fields=["filiere", "subject"], name="notes_profe_filiere_c6649f_idx"),
        ),
        migrations.AddIndex(
            model_name="professornote",
            index=models.Index(fields=["session", "semester"], name="notes_profe_session_0f9990_idx"),
        ),
        migrations.AddIndex(
            model_name="professornote",
            index=models.Index(fields=["created_at"], name="notes_profe_created_4ff1c7_idx"),
        ),
    ]
