# Generated by Django 5.0.6 on 2026-02-12 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportExportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("student_complete_record", "Student Complete Record"),
                            ("incident_report", "Incident Report"),
                            ("visitor_log", "Visitor Log Report"),
                            ("attendance_report", "Attendance Report"),
                            ("discipline_history", "Discipline History"),
                            ("attendance_csv", "Attendance CSV Export"),
                            ("attendance_xlsx", "Attendance Excel Export"),
                            ("grades_csv", "Grades CSV Export"),
                            ("grades_xlsx", "Grades Excel Export"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV"), ("xlsx", "Excel")], default="pdf", max_length=10
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Human-readable description of what was exported", max_length=300),
                ),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "export_reason",
                    models.TextField(blank=True, help_text="Reason for export - required for student complete records"),
                ),
                (
                    "student_id",
                    models.IntegerField(blank=True, help_text="Student PK if report is student-related", null=True),
                ),
                ("incident_id", models.IntegerField(blank=True, help_text="Incident PK if incident report", null=True)),
                ("filter_params", models.JSONField(blank=True, default=dict, help_text="Filter parameters applied")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "exported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_exports",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Export Log",
                "verbose_name_plural": "Report Export Logs",
                "ordering": ["-exported_at"],
                "indexes": [
                    models.Index(fields=["exported_by", "-exported_at"], name="rpt_user_date_idx"),
                    models.Index(fields=["report_type", "-exported_at"], name="rpt_type_date_idx"),
                ],
            },
        ),
    ]
