# Generated by Django 5.0.6 on 2026-02-12 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldChangeRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField(help_text="The PK of the object that was changed")),
                ("field_name", models.CharField(help_text="Name of the field that changed", max_length=100)),
                (
                    "field_verbose_name",
                    models.CharField(blank=True, help_text="Human-readable field name", max_length=200),
                ),
                ("old_value", models.TextField(blank=True, help_text="Previous field value as string", null=True)),
                ("new_value", models.TextField(blank=True, help_text="New field value as string", null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("change_reason", models.TextField(blank=True, help_text="Optional reason for the change")),
                (
                    "batch_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, help_text="Groups field changes from a single save operation"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Created"), ("update", "Updated"), ("delete", "Deleted")],
                        default="update",
                        max_length=10,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The model type that was changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Change Record",
                "verbose_name_plural": "Field Change Records",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(fields=["content_type", "object_id", "-changed_at"], name="audit_ct_obj_date_idx"),
                    models.Index(fields=["changed_by", "-changed_at"], name="audit_user_date_idx"),
                ],
            },
        ),
    ]
