# Generated by Django 5.0.6 on 2026-01-05 18:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_school_remove_newsandevents_summary_ru_and_more'),
        ('course', '0005_remove_course_summary_ru_remove_course_title_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Program Name')),
                ('code', models.CharField(help_text='Unique code for this program (e.g., CS, BA, ENG)', max_length=20, verbose_name='Program Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('level', models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree')], default='Bachelor', max_length=25, verbose_name='Level')),
                ('duration_years', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Duration (Years)')),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum number of students allowed in this program', null=True, verbose_name='Maximum Students')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive programs cannot accept new enrollments', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['professor', 'direction']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_filieres', to=settings.AUTH_USER_MODEL, verbose_name='Program Coordinator')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='core.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Filiere/Program',
                'verbose_name_plural': 'Filieres/Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FiliereRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('academic', 'Academic Qualification'), ('language', 'Language Proficiency'), ('exam', 'Entrance Exam'), ('document', 'Required Document'), ('other', 'Other')], max_length=50, verbose_name='Requirement Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Is Mandatory')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='filieres.filiere', verbose_name='Filiere')),
            ],
            options={
                'verbose_name': 'Filiere Requirement',
                'verbose_name_plural': 'Filiere Requirements',
                'ordering': ['order', 'requirement_type'],
            },
        ),
        migrations.CreateModel(
            name='FiliereSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Weight of this subject in final grade calculation', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Coefficient')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this subject is required or elective', verbose_name='Is Mandatory')),
                ('year', models.IntegerField(help_text='Which year of the program this subject belongs to', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Academic Year')),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4')], default=1, verbose_name='Semester')),
                ('credits', models.IntegerField(default=3, help_text='Number of academic credits for this subject', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Credits/ECTS')),
                ('hours_per_week', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Hours per Week')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='filieres.filiere', verbose_name='Filiere')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Subject/Course')),
            ],
            options={
                'verbose_name': 'Filiere Subject',
                'verbose_name_plural': 'Filiere Subjects',
                'ordering': ['year', 'semester', 'subject__title'],
            },
        ),
        migrations.AddIndex(
            model_name='filiere',
            index=models.Index(fields=['tenant', 'is_active'], name='filieres_fi_tenant__810804_idx'),
        ),
        migrations.AddIndex(
            model_name='filiere',
            index=models.Index(fields=['code'], name='filieres_fi_code_67da1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='filieresubject',
            index=models.Index(fields=['filiere', 'year', 'semester'], name='filieres_fi_filiere_262afd_idx'),
        ),
        migrations.AddIndex(
            model_name='filieresubject',
            index=models.Index(fields=['is_mandatory'], name='filieres_fi_is_mand_52e761_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filieresubject',
            unique_together={('filiere', 'subject', 'year', 'semester')},
        ),
    ]
