# Generated by Django 5.0.6 on 2026-01-05 19:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_student_drop_reason_student_graduation_date_and_more'),
        ('course', '0005_remove_course_summary_ru_remove_course_title_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=200)),
                ('curve_type', models.CharField(choices=[('linear', 'Linear Adjustment'), ('sqrt', 'Square Root Curve'), ('bell', 'Bell Curve'), ('custom', 'Custom')], max_length=20)),
                ('adjustment_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier for linear adjustment', max_digits=5)),
                ('add_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Points to add to all scores', max_digits=5)),
                ('mean_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('median_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('std_dev_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mean_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('median_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('std_dev_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_curves', to='course.course')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('passing_score', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_partial_credit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_rubrics', to='course.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rubrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=200)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='course.course')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_peer_reviews', to='accounts.student')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_peer_reviews', to='accounts.student')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.gradingrubric')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight as percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_points', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('excellent_description', models.TextField(blank=True, help_text='Description of excellent performance')),
                ('good_description', models.TextField(blank=True)),
                ('satisfactory_description', models.TextField(blank=True)),
                ('needs_improvement_description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='grading.gradingrubric')),
            ],
            options={
                'ordering': ['rubric', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RubricGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=200)),
                ('assignment_type', models.CharField(choices=[('essay', 'Essay'), ('project', 'Project'), ('presentation', 'Presentation'), ('lab', 'Lab Work'), ('other', 'Other')], max_length=50)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('letter_grade', models.CharField(blank=True, max_length=3)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('overall_feedback', models.TextField(blank=True)),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_grades_given', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grading.gradingrubric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_grades', to='accounts.student')),
            ],
            options={
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='CriterionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.rubriccriterion')),
                ('rubric_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_grades', to='grading.rubricgrade')),
            ],
        ),
        migrations.AddIndex(
            model_name='gradingrubric',
            index=models.Index(fields=['course', 'is_active'], name='grading_gra_course__f13365_idx'),
        ),
        migrations.AddIndex(
            model_name='peerreview',
            index=models.Index(fields=['reviewee', '-created_at'], name='grading_pee_reviewe_2caa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='peerreview',
            index=models.Index(fields=['reviewer', 'status'], name='grading_pee_reviewe_b3dd20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peerreview',
            unique_together={('assignment_name', 'reviewee', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='rubricgrade',
            index=models.Index(fields=['student', '-graded_at'], name='grading_rub_student_becde4_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricgrade',
            index=models.Index(fields=['rubric', '-graded_at'], name='grading_rub_rubric__a9cf85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='criteriongrade',
            unique_together={('rubric_grade', 'criterion')},
        ),
    ]
