# Generated by Django 5.0.6 on 2026-01-05 18:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_school_remove_newsandevents_summary_ru_and_more'),
        ('filieres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='Student Full Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nationality', models.CharField(default='', max_length=100, verbose_name='Nationality')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Parent/Guardian Name')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Parent Email')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Parent Phone')),
                ('parent_relationship', models.CharField(default='father', max_length=50, verbose_name='Relationship')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('level', models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree')], default='Bachelor', max_length=25)),
                ('previous_school', models.CharField(blank=True, max_length=200, verbose_name='Previous School')),
                ('enrollment_type', models.CharField(choices=[('new', 'New Student'), ('transfer', 'Transfer Student'), ('re_enrollment', 'Re-enrollment')], default='new', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('special_needs', models.TextField(blank=True, verbose_name='Special Needs/Requirements')),
                ('medical_information', models.TextField(blank=True, verbose_name='Medical Information')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_form', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled User Account')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='filieres.filiere', verbose_name='Program/Filiere')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_forms', to='core.school')),
            ],
            options={
                'verbose_name': 'Registration Form',
                'verbose_name_plural': 'Registration Forms',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='enrollment.registrationform')),
            ],
            options={
                'verbose_name': 'Enrollment Status History',
                'verbose_name_plural': 'Enrollment Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('photo', 'Student Photo'), ('transcript', 'Academic Transcript'), ('transfer_letter', 'Transfer Letter'), ('medical_certificate', 'Medical Certificate'), ('id_card', 'ID Card/Passport'), ('parent_id', 'Parent ID'), ('other', 'Other Document')], max_length=50, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='enrollment_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='Document File')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enrollment.registrationform')),
            ],
            options={
                'verbose_name': 'Enrollment Document',
                'verbose_name_plural': 'Enrollment Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='registrationform',
            index=models.Index(fields=['tenant', 'status'], name='enrollment__tenant__5e0a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationform',
            index=models.Index(fields=['academic_year', 'filiere'], name='enrollment__academi_548fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationform',
            index=models.Index(fields=['submitted_at'], name='enrollment__submitt_50ebcd_idx'),
        ),
    ]
