# Generated by Django 5.0.6 on 2026-02-12 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0002_remove_registrationform_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationform",
            name="parent_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_registrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Parent User Account",
            ),
        ),
    ]
