# Generated by Django 5.0.6 on 2026-02-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationform",
            name="address",
        ),
        migrations.RemoveField(
            model_name="registrationform",
            name="parent_name",
        ),
        migrations.RemoveField(
            model_name="registrationform",
            name="student_name",
        ),
        migrations.AddField(
            model_name="registrationform",
            name="city",
            field=models.CharField(default="", max_length=100, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="country",
            field=models.CharField(default="", max_length=100, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="parent_first_name",
            field=models.CharField(default="", max_length=100, verbose_name="Parent First Name"),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="parent_last_name",
            field=models.CharField(default="", max_length=100, verbose_name="Parent Last Name"),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="parent_middle_name",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Parent Middle Name"),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Postal Code"),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="province",
            field=models.CharField(default="", max_length=100, verbose_name="Province/State"),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="street_address",
            field=models.CharField(default="", max_length=255, verbose_name="Street Address"),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="student_first_name",
            field=models.CharField(default="", max_length=100, verbose_name="First Name"),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="student_last_name",
            field=models.CharField(default="", max_length=100, verbose_name="Last Name"),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="student_middle_name",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Middle Name"),
        ),
    ]
