# Generated by Django 5.0.6 on 2026-02-12 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_parent_custody_notes_parent_effective_from_and_more"),
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancereport",
            name="absence_notes",
            field=models.TextField(blank=True, help_text="Additional details about the absence"),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="absence_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unexcused", "Unexcused"),
                    ("medical", "Medical"),
                    ("family_emergency", "Family Emergency"),
                    ("court_date", "Court Date"),
                    ("suspension", "Suspension"),
                    ("school_event", "School Event"),
                    ("other", "Other"),
                ],
                help_text="Reason for absence (when status is absent)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="excused",
            field=models.BooleanField(
                default=False, help_text="Whether the absence has been excused by administration"
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="excused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="excused_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excused_absences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="supporting_document",
            field=models.FileField(
                blank=True, help_text="Medical certificate or supporting document", upload_to="absence_docs/%Y/%m/%d/"
            ),
        ),
        migrations.CreateModel(
            name="AbsenceNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "method",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("in_app", "In-App Notification")], max_length=10
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("parent_acknowledged", models.BooleanField(default=False)),
                ("parent_response", models.TextField(blank=True)),
                (
                    "attendance_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="attendance.attendancereport",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_notifications",
                        to="accounts.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Absence Notification",
                "verbose_name_plural": "Absence Notifications",
                "ordering": ["-sent_at"],
            },
        ),
    ]
