# Generated by Django 5.0.6 on 2026-02-12 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(help_text="Unique identifier, e.g. grade_sudden_jump", max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("grade", "Grade"),
                            ("payment", "Payment"),
                            ("enrollment", "Enrollment"),
                            ("login", "Login"),
                            ("academic", "Academic Integrity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "notify_roles",
                    models.JSONField(
                        blank=True, default=list, help_text='Roles to notify, e.g. ["direction","admin","professor"]'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Anomaly Type",
                "verbose_name_plural": "Anomaly Types",
                "ordering": ["domain", "severity", "code"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyThreshold",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(help_text="Threshold key, e.g. std_dev_multiplier", max_length=50)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "anomaly_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="anomaly_detection.anomalytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Threshold",
                "verbose_name_plural": "Anomaly Thresholds",
                "unique_together": {("anomaly_type", "key")},
            },
        ),
        migrations.CreateModel(
            name="AnomalyAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="new",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("email_sent", models.BooleanField(default=False)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomaly_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "anomaly_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="anomaly_detection.anomalytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Alert",
                "verbose_name_plural": "Anomaly Alerts",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(fields=["status", "-detected_at"], name="anomaly_det_status_538758_idx"),
                    models.Index(fields=["anomaly_type", "-detected_at"], name="anomaly_det_anomaly_718476_idx"),
                    models.Index(fields=["user", "-detected_at"], name="anomaly_det_user_id_aaac71_idx"),
                ],
            },
        ),
    ]
